### ISSUE TITLE
Architecture review, initial thoughts #1

### ISSUE THREAD

**Issue by rozyczko** [easyScience/easyCore#5]
Why is there a distinction between `easyCore` and `easyTemplateLib`? I don't see a clear separation of duties between these two.

- `easyCore` has data containers, so probably `core` is not the right monicker?
- I'm surprised to see graph analysis code here - isn't this something a utility library would do?

Actually, I think the current (and possibly planned) features of `easyCore` are mostly static classes and utility methods, like undo/redo, graph operations, (de)serialization, testing fixtures etc. Maybe `Core` is slightly misleading here?
Maybe `easyUtilities` or `easyAux` is a better name?

`easyCore` signifies indispensability, whereas I could imagine writing a class off of easyTemplateLib which doesn't reimplement any of the things from `easyCore`.

**Comment by AndrewSazonov** [comment]
`easyCore` is planned as a technique-independent python package. `easyTemplateLib` is, in contrast, a minimal working example of a technique-dependent python package which uses `easyCore`. When we need to create something useful, e.g., `easyDiffractionLib` or `easySpectroscopyLib`, we simply create new repositories choosing `easyTemplateLib` as the template repository in order to get the same directory structure and files as in `easyTemplateLib`. One can then modify `easyDiffractionLib` or `easySpectroscopyLib` according to their specific needs.

**Comment by rozyczko** [comment]
Yes, I understand the reason behind the split and desired architecture but I am commenting on the "pollution" of the word `core`.
Whereas certain functionality like undo/redo, object serialization etc are universal and should be included, I think that pure utility classes and methods should probably be taken out of core and placed elsewhere as they don't constitute the **core** functionality.
